// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pjvqlygmjmajpgitqmsx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBqdnFseWdtam1hanBnaXRxbXN4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg0NzU3ODksImV4cCI6MjA2NDA1MTc4OX0.EAh3BBfTMbpuhUWx2-DjFvsOiwXA-5snnp2A5J0VnzQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);